name: Actualizador Diario de Eventos

on:
  schedule:
    # Se ejecuta todos los días a las 8:00 AM (hora UTC)
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  actualizar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install requests google-generativeai ftplib

    - name: Ejecutar el script de Python
      run: python obtener_eventos.py
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        URL_FUENTE: ${{ secrets.URL_FUENTE }}
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USUARIO: ${{ secrets.FTP_USUARIO }}
        FTP_CONTRASENA: ${{ secrets.FTP_CONTRASENA }}
        NOMBRE_ARCHIVO_MENSAJE: ${{ secrets.NOMBRE_ARCHIVO_MENSAJE }}
